// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllBrands, getBrandById, createBrand, updateBrand, deleteBrand } from '@/services/brandService';
import type { BrandDto } from '@/types/brand';

export function useBrands(): { data: BrandDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['brand', 'getAllBrands'], queryFn: getAllBrands });
  return { data, isLoading, isError, error };
}

export function useBrandById(brandId: number): { data: BrandDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['brand', 'getBrandById', brandId], queryFn: () => getBrandById(brandId) });
  return { data, isLoading, isError, error };
}

export function useCreateBrand(): { mutate: (vars: BrandDto, options?: MutateOptions<BrandDto, Error, BrandDto>) => void; mutateAsync: (vars: BrandDto, options?: MutateOptions<BrandDto, Error, BrandDto>) => Promise<BrandDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: BrandDto) => createBrand(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['brand'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateBrand(): { mutate: (vars: { brandId: number; request: BrandDto }, options?: MutateOptions<BrandDto, Error, { brandId: number; request: BrandDto }>) => void; mutateAsync: (vars: { brandId: number; request: BrandDto }, options?: MutateOptions<BrandDto, Error, { brandId: number; request: BrandDto }>) => Promise<BrandDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ brandId, request }: { brandId: number; request: BrandDto }) => updateBrand(brandId, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['brand'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteBrand(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (brandId: number) => deleteBrand(brandId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['brand'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
