// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useUpcomingEvents(): { data: EventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useEventById(id: number): { data: EventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateEvent(): { mutate: (vars: EventDto, options?: MutateOptions<EventDto, Error, EventDto>) => void; mutateAsync: (vars: EventDto, options?: MutateOptions<EventDto, Error, EventDto>) => Promise<EventDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useEvents(): { data: EventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useAdminGetEventById(id: number): { data: EventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateEvent(): { mutate: (vars: { id: number; request: EventDto }, options?: MutateOptions<EventDto, Error, { id: number; request: EventDto }>) => void; mutateAsync: (vars: { id: number; request: EventDto }, options?: MutateOptions<EventDto, Error, { id: number; request: EventDto }>) => Promise<EventDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteEvent(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getUpcomingEvents, getEventById, createEvent, getAllEvents, adminGetEventById, updateEvent, deleteEvent } from '@/services/eventService';
import type { EventDto } from '@/types/event';

export function useUpcomingEvents(): { data: EventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['event', 'getUpcomingEvents'], queryFn: getUpcomingEvents });
  return { data, isLoading, isError, error };
}

export function useEventById(id: number): { data: EventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['event', 'getEventById', id], queryFn: () => getEventById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateEvent(): { mutate: (vars: EventDto, options?: MutateOptions<EventDto, Error, EventDto>) => void; mutateAsync: (vars: EventDto, options?: MutateOptions<EventDto, Error, EventDto>) => Promise<EventDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: EventDto) => createEvent(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['event'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useEvents(): { data: EventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['event', 'getAllEvents'], queryFn: getAllEvents });
  return { data, isLoading, isError, error };
}

export function useAdminGetEventById(id: number): { data: EventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['event', 'adminGetEventById', id], queryFn: () => adminGetEventById(id) });
  return { data, isLoading, isError, error };
}

export function useUpdateEvent(): { mutate: (vars: { id: number; request: EventDto }, options?: MutateOptions<EventDto, Error, { id: number; request: EventDto }>) => void; mutateAsync: (vars: { id: number; request: EventDto }, options?: MutateOptions<EventDto, Error, { id: number; request: EventDto }>) => Promise<EventDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: EventDto }) => updateEvent(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['event'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteEvent(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteEvent(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['event'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
