// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllEvents, getEventById, createEvent, updateEvent, deleteEvent } from '@/services/eventService';
import type { EventDto } from '@/types/event';

export function useEvents(): { data: EventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['event', 'getAllEvents'], queryFn: getAllEvents });
  return { data, isLoading, isError, error };
}

export function useEventById(eventId: number): { data: EventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['event', 'getEventById', eventId], queryFn: () => getEventById(eventId) });
  return { data, isLoading, isError, error };
}

export function useCreateEvent(): { mutate: (vars: EventDto, options?: MutateOptions<EventDto, Error, EventDto>) => void; mutateAsync: (vars: EventDto, options?: MutateOptions<EventDto, Error, EventDto>) => Promise<EventDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: EventDto) => createEvent(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['event'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateEvent(): { mutate: (vars: { eventId: number; request: EventDto }, options?: MutateOptions<EventDto, Error, { eventId: number; request: EventDto }>) => void; mutateAsync: (vars: { eventId: number; request: EventDto }, options?: MutateOptions<EventDto, Error, { eventId: number; request: EventDto }>) => Promise<EventDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ eventId, request }: { eventId: number; request: EventDto }) => updateEvent(eventId, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['event'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteEvent(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (eventId: number) => deleteEvent(eventId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['event'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
