// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useQuery } from '@tanstack/react-query';
import { getMyLoyaltyPoints } from '@/services/loyaltyService';
import type { LoyaltyPointsDto } from '@/types/loyalty';

export function useMyLoyaltyPoints(): { data: LoyaltyPointsDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['loyalty', 'getMyLoyaltyPoints'], queryFn: getMyLoyaltyPoints });
  return { data, isLoading, isError, error };
}
