// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useCreateOrder(): { mutate: (vars: CreateOrderRequest, options?: MutateOptions<OrderDto, Error, CreateOrderRequest>) => void; mutateAsync: (vars: CreateOrderRequest, options?: MutateOptions<OrderDto, Error, CreateOrderRequest>) => Promise<OrderDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useOrdersByUserId(): { data: OrderDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useOrderById(orderId: number): { data: OrderDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useOrders(): { data: OrderDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useAdminGetOrderById(orderId: number): { data: OrderDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateOrderStatus(): { mutate: (vars: { orderId: number; request: OrderStatus }, options?: MutateOptions<OrderDto, Error, { orderId: number; request: OrderStatus }>) => void; mutateAsync: (vars: { orderId: number; request: OrderStatus }, options?: MutateOptions<OrderDto, Error, { orderId: number; request: OrderStatus }>) => Promise<OrderDto>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { createOrder, getOrdersByUserId, getOrderById, getAllOrders, adminGetOrderById, updateOrderStatus, cancelOrder } from '@/services/orderService';
import type { CreateOrderRequest, OrderDto, OrderStatus } from '@/types/order';

export function useCreateOrder(): { mutate: (vars: CreateOrderRequest, options?: MutateOptions<OrderDto, Error, CreateOrderRequest>) => void; mutateAsync: (vars: CreateOrderRequest, options?: MutateOptions<OrderDto, Error, CreateOrderRequest>) => Promise<OrderDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateOrderRequest) => createOrder(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useOrdersByUserId(): { data: OrderDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getOrdersByUserId'], queryFn: getOrdersByUserId });
  return { data, isLoading, isError, error };
}

export function useCancelOrder(): { mutate: (vars: number, options?: MutateOptions<OrderDto, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<OrderDto, Error, number>) => Promise<OrderDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (orderId: number) => cancelOrder(orderId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useOrderById(orderId: number): { data: OrderDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getOrderById', orderId], queryFn: () => getOrderById(orderId), enabled: orderId > 0 });
  return { data, isLoading, isError, error };
}

export function useOrders(): { data: OrderDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getAllOrders'], queryFn: getAllOrders });
  return { data, isLoading, isError, error };
}

export function useAdminGetOrderById(orderId: number): { data: OrderDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'adminGetOrderById', orderId], queryFn: () => adminGetOrderById(orderId) });
  return { data, isLoading, isError, error };
}

export function useUpdateOrderStatus(): { mutate: (vars: { orderId: number; request: OrderStatus }, options?: MutateOptions<OrderDto, Error, { orderId: number; request: OrderStatus }>) => void; mutateAsync: (vars: { orderId: number; request: OrderStatus }, options?: MutateOptions<OrderDto, Error, { orderId: number; request: OrderStatus }>) => Promise<OrderDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ orderId, request }: { orderId: number; request: OrderStatus }) => updateOrderStatus(orderId, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
