// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { createOrder, getAllOrders, getOrderById, adminGetAllOrders, updateOrderStatus } from '@/services/orderService';
import type { CreateOrderRequest, OrderResponse } from '@/types/order';

export function useCreateOrder(): { mutate: (vars: CreateOrderRequest, options?: MutateOptions<OrderResponse, Error, CreateOrderRequest>) => void; mutateAsync: (vars: CreateOrderRequest, options?: MutateOptions<OrderResponse, Error, CreateOrderRequest>) => Promise<OrderResponse>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateOrderRequest) => createOrder(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useOrders(): { data: OrderResponse[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getAllOrders'], queryFn: getAllOrders });
  return { data, isLoading, isError, error };
}

export function useOrderById(orderId: number): { data: OrderResponse | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getOrderById', orderId], queryFn: () => getOrderById(orderId) });
  return { data, isLoading, isError, error };
}

export function useAdminGetAllOrders(): { data: OrderResponse[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'adminGetAllOrders'], queryFn: adminGetAllOrders });
  return { data, isLoading, isError, error };
}

export function useUpdateOrderStatus(): { mutate: (vars: number, options?: MutateOptions<OrderResponse, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<OrderResponse, Error, number>) => Promise<OrderResponse>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (orderId: number) => updateOrderStatus(orderId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
