// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useCreateOrder(): { mutate: (vars: CreateOrderRequest, options?: MutateOptions<OrderResponse, Error, CreateOrderRequest>) => void; mutateAsync: (vars: CreateOrderRequest, options?: MutateOptions<OrderResponse, Error, CreateOrderRequest>) => Promise<OrderResponse>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useMyOrders(): { data: OrderResponse[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useOrders(): { data: OrderResponse[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useOrderById(orderId: number): { data: OrderResponse | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateOrderStatus(): { mutate: (vars: { orderId: number; request: UpdateOrderStatusRequest }, options?: MutateOptions<OrderResponse, Error, { orderId: number; request: UpdateOrderStatusRequest }>) => void; mutateAsync: (vars: { orderId: number; request: UpdateOrderStatusRequest }, options?: MutateOptions<OrderResponse, Error, { orderId: number; request: UpdateOrderStatusRequest }>) => Promise<OrderResponse>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { createOrder, getMyOrders, getAllOrders, getOrderById, updateOrderStatus } from '@/services/orderService';
import type { CreateOrderRequest, OrderResponse, UpdateOrderStatusRequest } from '@/types/order';

export function useCreateOrder(): { mutate: (vars: CreateOrderRequest, options?: MutateOptions<OrderResponse, Error, CreateOrderRequest>) => void; mutateAsync: (vars: CreateOrderRequest, options?: MutateOptions<OrderResponse, Error, CreateOrderRequest>) => Promise<OrderResponse>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateOrderRequest) => createOrder(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useMyOrders(): { data: OrderResponse[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getMyOrders'], queryFn: getMyOrders });
  return { data, isLoading, isError, error };
}

export function useOrders(): { data: OrderResponse[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getAllOrders'], queryFn: getAllOrders });
  return { data, isLoading, isError, error };
}

export function useOrderById(orderId: number): { data: OrderResponse | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['order', 'getOrderById', orderId], queryFn: () => getOrderById(orderId) });
  return { data, isLoading, isError, error };
}

export function useUpdateOrderStatus(): { mutate: (vars: { orderId: number; request: UpdateOrderStatusRequest }, options?: MutateOptions<OrderResponse, Error, { orderId: number; request: UpdateOrderStatusRequest }>) => void; mutateAsync: (vars: { orderId: number; request: UpdateOrderStatusRequest }, options?: MutateOptions<OrderResponse, Error, { orderId: number; request: UpdateOrderStatusRequest }>) => Promise<OrderResponse>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ orderId, request }: { orderId: number; request: UpdateOrderStatusRequest }) => updateOrderStatus(orderId, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['order'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
