// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllProducts, getProductById, createProduct, updateProduct, deleteProduct, updateProductStock } from '@/services/productService';
import type { ProductDto } from '@/types/product';

export function useProducts(): { data: void | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getAllProducts'], queryFn: getAllProducts });
  return { data, isLoading, isError, error };
}

export function useProductById(productId: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getProductById', productId], queryFn: () => getProductById(productId) });
  return { data, isLoading, isError, error };
}

export function useCreateProduct(): { mutate: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => void; mutateAsync: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ProductDto) => createProduct(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateProduct(): { mutate: (vars: { productId: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { productId: number; request: ProductDto }>) => void; mutateAsync: (vars: { productId: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { productId: number; request: ProductDto }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ productId, request }: { productId: number; request: ProductDto }) => updateProduct(productId, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteProduct(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (productId: number) => deleteProduct(productId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateProductStock(): { mutate: (vars: { productId: number; request: unknown }, options?: MutateOptions<ProductDto, Error, { productId: number; request: unknown }>) => void; mutateAsync: (vars: { productId: number; request: unknown }, options?: MutateOptions<ProductDto, Error, { productId: number; request: unknown }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ productId, request }: { productId: number; request: unknown }) => updateProductStock(productId, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
