// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useProducts(): { data: void | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useProductById(id: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCategories(): { data: ProductCategory[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useBrands(): { data: Brand[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateProduct(): { mutate: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => void; mutateAsync: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateProduct(): { mutate: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => void; mutateAsync: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteProduct(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateProductStock(): { mutate: (vars: { id: number; request: unknown }, options?: MutateOptions<ProductDto, Error, { id: number; request: unknown }>) => void; mutateAsync: (vars: { id: number; request: unknown }, options?: MutateOptions<ProductDto, Error, { id: number; request: unknown }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useAdminGetAllProducts(): { data: void | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useAdminGetProductById(id: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useAdminGetAllCategories(): { data: ProductCategory[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateCategory(): { mutate: (vars: ProductCategory, options?: MutateOptions<ProductCategory, Error, ProductCategory>) => void; mutateAsync: (vars: ProductCategory, options?: MutateOptions<ProductCategory, Error, ProductCategory>) => Promise<ProductCategory>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateCategory(): { mutate: (vars: { id: number; request: ProductCategory }, options?: MutateOptions<ProductCategory, Error, { id: number; request: ProductCategory }>) => void; mutateAsync: (vars: { id: number; request: ProductCategory }, options?: MutateOptions<ProductCategory, Error, { id: number; request: ProductCategory }>) => Promise<ProductCategory>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteCategory(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useAdminGetAllBrands(): { data: Brand[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateBrand(): { mutate: (vars: Brand, options?: MutateOptions<Brand, Error, Brand>) => void; mutateAsync: (vars: Brand, options?: MutateOptions<Brand, Error, Brand>) => Promise<Brand>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateBrand(): { mutate: (vars: { id: number; request: Brand }, options?: MutateOptions<Brand, Error, { id: number; request: Brand }>) => void; mutateAsync: (vars: { id: number; request: Brand }, options?: MutateOptions<Brand, Error, { id: number; request: Brand }>) => Promise<Brand>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteBrand(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllProducts, getProductById, getAllCategories, getAllBrands, createProduct, updateProduct, deleteProduct, updateProductStock, adminGetAllProducts, adminGetProductById, adminGetAllCategories, createCategory, updateCategory, deleteCategory, adminGetAllBrands, createBrand, updateBrand, deleteBrand } from '@/services/productService';
import type { Brand } from '@/types/brand';
import type { ProductCategory, ProductDto } from '@/types/product';

export function useProducts(): { data: void | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getAllProducts'], queryFn: getAllProducts });
  return { data, isLoading, isError, error };
}

export function useProductById(id: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getProductById', id], queryFn: () => getProductById(id) });
  return { data, isLoading, isError, error };
}

export function useCategories(): { data: ProductCategory[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getAllCategories'], queryFn: getAllCategories });
  return { data, isLoading, isError, error };
}

export function useBrands(): { data: Brand[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getAllBrands'], queryFn: getAllBrands });
  return { data, isLoading, isError, error };
}

export function useCreateProduct(): { mutate: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => void; mutateAsync: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ProductDto) => createProduct(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateProduct(): { mutate: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => void; mutateAsync: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: ProductDto }) => updateProduct(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteProduct(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteProduct(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateProductStock(): { mutate: (vars: { id: number; request: unknown }, options?: MutateOptions<ProductDto, Error, { id: number; request: unknown }>) => void; mutateAsync: (vars: { id: number; request: unknown }, options?: MutateOptions<ProductDto, Error, { id: number; request: unknown }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: unknown }) => updateProductStock(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useAdminGetAllProducts(): { data: void | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'adminGetAllProducts'], queryFn: adminGetAllProducts });
  return { data, isLoading, isError, error };
}

export function useAdminGetProductById(id: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'adminGetProductById', id], queryFn: () => adminGetProductById(id) });
  return { data, isLoading, isError, error };
}

export function useAdminGetAllCategories(): { data: ProductCategory[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'adminGetAllCategories'], queryFn: adminGetAllCategories });
  return { data, isLoading, isError, error };
}

export function useCreateCategory(): { mutate: (vars: ProductCategory, options?: MutateOptions<ProductCategory, Error, ProductCategory>) => void; mutateAsync: (vars: ProductCategory, options?: MutateOptions<ProductCategory, Error, ProductCategory>) => Promise<ProductCategory>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ProductCategory) => createCategory(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateCategory(): { mutate: (vars: { id: number; request: ProductCategory }, options?: MutateOptions<ProductCategory, Error, { id: number; request: ProductCategory }>) => void; mutateAsync: (vars: { id: number; request: ProductCategory }, options?: MutateOptions<ProductCategory, Error, { id: number; request: ProductCategory }>) => Promise<ProductCategory>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: ProductCategory }) => updateCategory(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteCategory(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteCategory(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useAdminGetAllBrands(): { data: Brand[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'adminGetAllBrands'], queryFn: adminGetAllBrands });
  return { data, isLoading, isError, error };
}

export function useCreateBrand(): { mutate: (vars: Brand, options?: MutateOptions<Brand, Error, Brand>) => void; mutateAsync: (vars: Brand, options?: MutateOptions<Brand, Error, Brand>) => Promise<Brand>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: Brand) => createBrand(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateBrand(): { mutate: (vars: { id: number; request: Brand }, options?: MutateOptions<Brand, Error, { id: number; request: Brand }>) => void; mutateAsync: (vars: { id: number; request: Brand }, options?: MutateOptions<Brand, Error, { id: number; request: Brand }>) => Promise<Brand>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: Brand }) => updateBrand(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteBrand(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteBrand(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
