// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useSubmitReview(): { mutate: (vars: ReviewDto, options?: MutateOptions<ReviewDto, Error, ReviewDto>) => void; mutateAsync: (vars: ReviewDto, options?: MutateOptions<ReviewDto, Error, ReviewDto>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useReviewsByProductId(productId: number): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract usePendingReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useApproveReview(): { mutate: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useRejectReview(): { mutate: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteReview(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { submitReview, getReviewsByProductId, getAllReviews, getPendingReviews, approveReview, rejectReview, deleteReview } from '@/services/reviewService';
import type { ReviewDto } from '@/types/review';

export function useSubmitReview(): { mutate: (vars: ReviewDto, options?: MutateOptions<ReviewDto, Error, ReviewDto>) => void; mutateAsync: (vars: ReviewDto, options?: MutateOptions<ReviewDto, Error, ReviewDto>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ReviewDto) => submitReview(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useReviewsByProductId(productId: number): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getReviewsByProductId', productId], queryFn: () => getReviewsByProductId(productId) });
  return { data, isLoading, isError, error };
}

export function useReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getAllReviews'], queryFn: getAllReviews });
  return { data, isLoading, isError, error };
}

export function usePendingReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getPendingReviews'], queryFn: getPendingReviews });
  return { data, isLoading, isError, error };
}

export function useApproveReview(): { mutate: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (reviewId: number) => approveReview(reviewId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useRejectReview(): { mutate: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<ReviewDto, Error, number>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (reviewId: number) => rejectReview(reviewId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteReview(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (reviewId: number) => deleteReview(reviewId),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
