// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { createReview, getReviewsByProductId, getAllReviews } from '@/services/reviewService';
import type { CreateReviewRequest, ReviewDto } from '@/types/review';

export function useCreateReview(): { mutate: (vars: CreateReviewRequest, options?: MutateOptions<ReviewDto, Error, CreateReviewRequest>) => void; mutateAsync: (vars: CreateReviewRequest, options?: MutateOptions<ReviewDto, Error, CreateReviewRequest>) => Promise<ReviewDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: CreateReviewRequest) => createReview(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['review'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useReviewsByProductId(productId: number): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getReviewsByProductId', productId], queryFn: () => getReviewsByProductId(productId) });
  return { data, isLoading, isError, error };
}

export function useReviews(): { data: ReviewDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['review', 'getAllReviews'], queryFn: getAllReviews });
  return { data, isLoading, isError, error };
}
