// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllEvents, getUpcomingEvents, getEventById, adminGetAllEvents, adminGetEventById, createEvent, updateEvent, deleteEvent } from '@/services/storeEventService';
import type { StoreEventDto } from '@/types/storeEvent';

export function useEvents(): { data: StoreEventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['storeEvent', 'getAllEvents'], queryFn: getAllEvents });
  return { data, isLoading, isError, error };
}

export function useUpcomingEvents(): { data: StoreEventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['storeEvent', 'getUpcomingEvents'], queryFn: getUpcomingEvents });
  return { data, isLoading, isError, error };
}

export function useEventById(id: number): { data: StoreEventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['storeEvent', 'getEventById', id], queryFn: () => getEventById(id) });
  return { data, isLoading, isError, error };
}

export function useAdminGetAllEvents(): { data: StoreEventDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['storeEvent', 'adminGetAllEvents'], queryFn: adminGetAllEvents });
  return { data, isLoading, isError, error };
}

export function useAdminGetEventById(id: number): { data: StoreEventDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['storeEvent', 'adminGetEventById', id], queryFn: () => adminGetEventById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateEvent(): { mutate: (vars: StoreEventDto, options?: MutateOptions<StoreEventDto, Error, StoreEventDto>) => void; mutateAsync: (vars: StoreEventDto, options?: MutateOptions<StoreEventDto, Error, StoreEventDto>) => Promise<StoreEventDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: StoreEventDto) => createEvent(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['storeEvent'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateEvent(): { mutate: (vars: { id: number; request: StoreEventDto }, options?: MutateOptions<StoreEventDto, Error, { id: number; request: StoreEventDto }>) => void; mutateAsync: (vars: { id: number; request: StoreEventDto }, options?: MutateOptions<StoreEventDto, Error, { id: number; request: StoreEventDto }>) => Promise<StoreEventDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: StoreEventDto }) => updateEvent(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['storeEvent'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteEvent(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteEvent(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['storeEvent'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
