// Business-specific site configuration — generated by the pipeline per business.
// Edit this file to change the site's branding, navigation, and design tokens.
// All values are passed as props to SiteHeader and SiteFooter via SiteLayout in App.tsx.
import type { SiteConfig } from '@/shell';

const siteConfig: SiteConfig = {
  header: {
    brandName: 'My Business',
    logoUrl: null,
    navLinks: [],
    ctaButton: null,
    showAuth: true,
    bgClass: 'bg-gray-900',
    textClass: 'text-white',
    hoverClass: 'hover:text-blue-400',
    ctaClass: 'bg-blue-500 text-white hover:bg-blue-600',
  },
  footer: {
    brandName: 'My Business',
    tagline: null,
    address: null,
    phone: null,
    email: null,
    openingHours: null,
    quickLinks: [],
    socialLinks: [],
    bgClass: 'bg-gray-900',
    textClass: 'text-gray-400',
    accentClass: 'hover:text-blue-400',
  },
};

export default siteConfig;
